ALTER TABLE listings ADD COLUMN condition TEXT NOT NULL DEFAULT 'używany_dobry';
ALTER TABLE listings ADD COLUMN city TEXT NOT NULL DEFAULT '';
ALTER TABLE listings ADD COLUMN negotiable INTEGER NOT NULL DEFAULT 1;
ALTER TABLE listings ADD COLUMN shipping INTEGER NOT NULL DEFAULT 0;
